mysite/board/urls.py
from django.urls import path

from . import views 

app_name = 'board'
urlpatterns = [
    path('', views.index, name='index'),
    path('signup', views.signup, name='signup'),
    path('users/<int:user_id>', views.user, name='user'),
    path('posts/<int:post_id>', views.post, name='post'),
    path('compose', views.compose_post, name='compose_post'),
    path('logout', views.logout_user, name='logout'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

mysite/board/models.py
# Create your models here.
from django.db import models
from django.db.models.deletion import CASCADE
from django.db.models.fields.mixins import FieldCacheMixin
from django.contrib.auth.models import User


# Create your models here.
class Post(models.Model):
    content = models.TextField()
    user = models.ForeignKey(User, on_delete=CASCADE, related_name='posts')
    date_posted = models.DateTimeField('date_posted', auto_now=True)
    
    def __str__(self):
        return '{} says {}'.format(self.user.username, self.content)

class Comment(models.Model):
    post = models.ForeignKey('Post', on_delete=CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=CASCADE)
    content = models.TextField()

    def __str__(self):
        return self.content[:50]

class Follow(models.Model):
    user_from = models.ForeignKey(User, on_delete=CASCADE, related_name='following')
    user_to = models.ForeignKey(User, on_delete=CASCADE, related_name='followers')

    def __str__(self):
        return '{} follows {}'.format(self.user_from, self.user_to)

mysite/board/forms.py
from django.forms import ModelForm
from .models import Post, Comment

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'content'
        ]

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'content'
        ]

mysite/board/views.py
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from django.http.response import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.decorators import login_required
from .forms import PostForm, CommentForm
from .models import Post, Follow

from django.conf import settings

def index(request):
  users = User.objects.all()
  if not request.user.is_authenticated:
    return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
  followings = request.user.following.all()
  posts = []
  for following in followings:
    user = following.user_to
    user_posts = Post.objects.filter(user=user)[:5]
    for t in user_posts:
      posts.append(t)
  context = {
    'user': request.user,
    'posts': posts,
    'users': users
  }
  return render(request, 'board/index.html', context)

def logout_user(request):
    logout(request)
    return redirect('board:index')

def signup(request):
    if request.method == 'POST':
        # validate user, save to db, redirect
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # save user
            form.save()
            # log user in
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            # redirect
            return redirect('board:index')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})

@login_required()
def compose_post(request):
    current_user = request.user
    user = User.objects.get(id=current_user.id)
    users = User.objects.all()
    if request.method == 'POST':
        form = PostForm(request.POST)
        # validate
        if form.is_valid():
            new_post = form.save(commit=False)
            # add current_user id
            new_post.user = user
            # save db
            new_post.save()
            # redirect
            return redirect('board:index', current_user.id)
    else:
        form = PostForm()
    context = {
        'form' : form,
        'users': users
    }
    return render(request, 'board/compose_post.html', context)

# post page, shows the post and all its comments
def post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    users = User.objects.all()
    comments = post.comments
    context = {
        'post': post,
        'comments': comments,
        'current_user': request.user,
        'users': users
    }
    # add comment as the current user
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.post = post
            new_comment.user = request.user
            new_comment.save()
    else:
        form = CommentForm()
    context['comment_form'] = form
    return render(request, 'board/post.html', context)

@login_required()
def user(request, user_id):
    current_user = request.user
    user = get_object_or_404(User, pk=user_id)
    users = User.objects.all()
    posts = user.posts.all()[:20]
    context = {
        'current_user': current_user,
        'user': user,
        'posts': posts,
        'users': users
    }
# is the current user already following page's user
    already_following = Follow.objects.filter(user_from=current_user, user_to=user_id).exists()
    context['is_following'] = already_following
    if request.method == 'POST':
        if already_following:
            #unfollow
            follow = Follow.objects.get(user_from=current_user, user_to=user_id)
            follow.delete()
        else:
            #follow
            follow = Follow(user_from=current_user, user_to=user)
            follow.save()
        return redirect('board:user', user_id)
    return render(request, 'board/user.html', context)

mysite/board/templates/board/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Message Board</title>
  </head>
  <body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'board:index' %}">Message Board</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link bg-primary text-white" href="{% url 'board:compose_post' %}">Post <span class="sr-only">(current)</span></a>
      </li>
    </ul>
  {% if user.is_authenticated %}
  <form class="form-inline">
    <a class="btn my-2 my-sm-0" href="{% url 'board:logout' %}">Log out</a>
  </form>
  {% endif %}
  </div>
  </nav>

  <div class="mt-1"></div>

  <div class="container">
  <div class="row">
    <div class="col-sm-8">
      {% block content %}
      {% endblock %}
    </div>

    <div class="col-sm-4">
      <div class="mt-3"></div>
      <h3> You may be interested in </h3>
      <ul class="list-group">
        {% for user in users %}
          <li class="list-group-item"><a href="{% url 'board:user' user.id %}">{{ user.username }}</a></li>
        {% endfor %}
      </ul>
    </div>
  </div>
  </div>
  </body>
</html>

mysite/board/templates/board/compose.html
<h1>What's happening</h1>

{% load crispy_forms_tags %}
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="post">
</form>

mysite/board/templates/board/compose_post.html
{% extends "board/base.html" %}
{% block content %}
<h1>What's happening</h1>

{% load crispy_forms_tags %}
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="post">
</form>
{% endblock %}

mysite/board/templates/board/index.html
<h1>Hi, {{ username }} </h1>

<a href="{% url 'board:logout_user' %}">logout</a>

mysite/board/templates/board/post.html
{% extends "board/base.html" %}
{% block content %}
<h2> {{ post.content }} </h2>

{% for comment in post.comments.all %}
    <div class="card">
      <div class="card-header">
        {{ comment.user.username }}
      </div>
      <div class="card-body">
        <p class="card-text">{{ comment.content }}</p>
      </div>
    </div>
    <div class="mb-3"></div>
{% endfor %}

{% if current_user.id is not None %}
Add a comment

{% load crispy_forms_tags %}
<form method="post">
  {% csrf_token %}
  {{ comment_form|crispy }}
  <input type="submit" value="Add" class="btn btn-primary" />
</form>
{% else %}
<a href="/accounts/login">Log in</a> to leave a comment
{% endif %}
{% endblock %}

mysite/board/templates/board/user.html
{% extends "board/base.html" %}
{% block content %}
{% load crispy_forms_tags %}
<h1>{{ user.username }}</h1>
<p>{{ user.following.count }} Following   {{ user.followers.count }} Followers</p>

{% if current_user.id is not None and current_user.id != user.id %}
  <form method="post">
    {% csrf_token %}
    {% if is_following %}
      <input type="submit" value="Unfollow" class="btn btn-primary" />
    {% else %}
      <input type="submit" value="Follow" class="btn btn-primary" />
    {% endif %}
  </form>
{% endif %}

  <div class="mb-3"></div>
  {% for post in posts %}
    <div class="card">
      <div class="card-header">
        <a href="{% url 'board:post' post.user.id %}"> {{ post.user.username }}</a>
      </div>
      <div class="card-body">
        <p class="card-text">{{ post.content }}</p>
      </div>
      <div class="card-footer text-muted">
        <div class="row">
          <div class="col"><p class="mb-0"><a href="{% url 'board:post' post.id %}">{{ post.comments.count }} comments</a></p></div>
          <div class="col"><p class="mb-0 text-right">{{ post.date_posted|date:'Y-m-d' }}</p></div>
        </div>
      </div>
    </div>
    <div class="mb-3"></div>
  {% endfor %}

{% endblock %}